{
    "metadata" :
    {
        "formatVersion" : 3,
        "generatedBy"   : "ParametricParts",
        "vertices"      : 8,
        "faces"         : 12,
        "normals"       : 0,
        "colors"        : 0,
        "uvs"           : 0,
        "materials"     : 1,
        "morphTargets"  : 0
    },

    "scale" : 1.0,

    "materials": [    {
    "DbgColor" : 15658734,
    "DbgIndex" : 0,
    "DbgName" : "Material",
    "colorAmbient" : [0.0, 0.0, 0.0],
    "colorDiffuse" : [0.6400000190734865, 0.10179081114814892, 0.126246120426746],
    "colorSpecular" : [0.5, 0.5, 0.5],
    "shading" : "Lambert",
    "specularCoef" : 50,
    "transparency" : 1.0,
    "vertexColors" : false
    }],

    "vertices": [-40.0, 30.0, -5.0, -40.0, -30.0, 5.0, -40.0, 30.0, 5.0, -40.0, -30.0, -5.0, 40.0, -30.0, 5.0, 40.0, 30.0, -5.0, 40.0, 30.0, 5.0, 40.0, -30.0, -5.0],

    "morphTargets": [],

    "normals": [],

    "colors": [],

    "uvs": [[]],

    "faces": [0, 0, 1, 2, 0, 3, 1, 0, 0, 4, 5, 6, 0, 4, 7, 5, 0, 3, 7, 1, 0, 7, 4, 1, 0, 5, 0, 2, 0, 6, 5, 2, 0, 0, 5, 3, 0, 3, 5, 7, 0, 6, 2, 1, 0, 6, 1, 4]
}
